import React, { useState } from "react";

export function AiTutorView() {
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState([
    {
      role: "assistant",
      content: "Hello! I am your interactive studyniq AI companion. Drop a question below to explain any confusing textbook concepts!"
    }
  ]);
  const [loading, setLoading] = useState(false);

  // Safely reference the environment key to prevent production bundler panics
  const apiKey = import.meta.env.VITE_GROQ_API_KEY || "";

  const sendMessage = async () => {
    if (!question.trim()) return;

    const userMessage = {
      role: "user",
      content: question.trim()
    };

    // 1. Immediately append the user's message to the UI feed and clear the input
    setMessages((prev) => [...prev, userMessage]);
    setQuestion("");
    setLoading(true);

    try {
      // 2. Make the direct connection to the Groq Chat Completion endpoint
      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            {
              role: "system",
              content: "You are StudyNiq AI Tutor. Explain concepts clearly for secondary school and GCSE students."
            },
            ...messages,
            userMessage
          ]
        })
      });

      if (!response.ok) {
        throw new Error(`Groq API returned status: ${response.status}`);
      }

      const data = await response.json();
      
      // 3. Extract the text response text generated by the AI model safely
      const aiReply = {
        role: "assistant",
        content: data?.choices?.[0]?.message?.content || "Sorry, I couldn't generate a response."
      };

      // 4. Append the assistant response to display it on screen
      setMessages((prev) => [...prev, aiReply]);
    } catch (error) {
      console.error("Chat Error:", error);
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "System connection error. Please verify your API keys or network status."
        }
      ]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 flex flex-col h-[calc(100vh-220px)]">
      <div>
        <h2 className="text-xl font-bold text-gray-900">AI Tutor Chat</h2>
        <p className="text-xs text-gray-400 mt-1">
          Ask questions, simplify jargon, or review textbook core logic.
        </p>
      </div>

      <div className="bg-white border border-gray-100 rounded-3xl flex-1 p-6 shadow-sm flex flex-col overflow-hidden">
        {/* Chat Feed */}
        <div className="space-y-4 overflow-y-auto flex-1 pr-1 pb-4">
          {messages.map((msg, index) => (
            <div
              key={index}
              className={`flex gap-3 ${msg.role === "user" ? "justify-end" : ""}`}
            >
              {msg.role === "assistant" && (
                <div className="w-7 h-7 bg-indigo-100 text-indigo-600 text-xs rounded-xl flex items-center justify-center font-bold shrink-0">
                  🤖
                </div>
              )}
              
              <div
                className={`p-3 rounded-2xl text-xs font-medium leading-relaxed max-w-[80%] ${
                  msg.role === "user"
                    ? "bg-indigo-600 text-white"
                    : "bg-gray-50 border border-gray-100 text-gray-700"
                }`}
              >
                {msg.content}
              </div>
            </div>
          ))}
          
          {loading && (
            <div className="text-xs text-gray-400 flex items-center gap-2 italic">
              <span className="animate-pulse">● ● ●</span> AI is thinking...
            </div>
          )}
        </div>

        {/* Input Controls */}
        <div className="flex gap-2 pt-4 border-t border-gray-50">
          <input
            type="text"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && sendMessage()}
            placeholder="Ask a question..."
            disabled={loading}
            className="flex-1 p-3 text-xs bg-gray-50 border border-gray-100 rounded-xl focus:outline-none focus:border-indigo-500 font-medium disabled:opacity-60"
          />
          <button
            type="button"
            onClick={sendMessage}
            disabled={loading || !question.trim()}
            className="bg-indigo-600 text-white px-4 text-xs font-bold rounded-xl hover:bg-indigo-700 transition-colors disabled:opacity-50"
          >
            Send
          </button>
        </div>
      </div>
    </div>
  );
}

export function NotesView() {
  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold text-gray-900">Workspace Notes</h2>
          <p className="text-xs text-gray-400 mt-1">Organize and compose summaries of class lecture details.</p>
        </div>
        <button className="bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold px-4 py-2 rounded-xl transition-all shadow-sm">
          + New Document
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-white border border-gray-100 p-4 rounded-2xl shadow-sm cursor-pointer hover:border-gray-200 transition-all flex justify-between items-center">
          <div>
            <h4 className="font-bold text-xs text-gray-900">🧬 Mitosis Structural Breakdown</h4>
            <p className="text-[10px] text-gray-400 mt-1">Updated 2 hours ago</p>
          </div>
          <span className="text-xs">📝</span>
        </div>
      </div>
    </div>
  );
}